apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-service.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ai-service.name" . }}
    {{- include "ai-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "ai-service.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "frontend.name" . }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{ include "chat-history-service.name" . }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
