apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-service.fullname" . }}
spec:
  selector:
    app: {{ include "ai-service.fullname" . }}
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
