apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-service.fullname" . }}
  labels:
    app: {{ include "ai-service.name" . }}
    {{- include "ai-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ai-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-service.name" . }}
        {{- include "ai-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ai-service.fullname" . }}-sa
      containers:
      - name: {{ include "ai-service.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-service-secrets
              key: GOOGLE_API_KEY
        - name: CHAT_HISTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              # This line is changed to reference the templated ConfigMap name
              name: {{ include "ai-service.fullname" . }}-config
              key: chatHistoryUrl
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
